image: ebits/openshift-client

stages:
  - deployToOpenShift

variables:
  OPENSHIFT_SERVER: https://openshift.ext.cetic.be:8443
  OPENSHIFT_DOMAIN: openshift.ext.cetic.be
  # Configure this variable in Secure Variables:
  # OPENSHIFT_TOKEN: my.openshift.token

.deploy: &deploy
  before_script:
    - oc login "$OPENSHIFT_SERVER" --token="$OPENSHIFT_TOKEN" --insecure-skip-tls-verify
    - oc project "<YOUR OC PROJECT NAME HERE>"
  script:
    - "oc get services $APP 2> /dev/null || oc new-app . --name=$APP"
    - "oc start-build $APP --from-dir=. --follow || sleep 3s"
    - "oc get routes $APP 2> /dev/null || oc expose service $APP --hostname=$APP_HOST"

prod:
  <<: *deploy
  stage: deployToOpenShift
  tags:
    - docker
  variables:
    APP: <YOUR EC PROJECT NAME HERE>
    # this is your app domain name exposed by OpenShift (usually myapp.openshift.ext.cetic.be)
    APP_HOST: <YOUR EC PROJECT DOMAIN NAME HERE>.$OPENSHIFT_DOMAIN
  environment:
    name: master
    url: http://<YOUR EC PROJECT DOMAIN NAME HERE>.$OPENSHIFT_DOMAIN
  only:
    - master

